import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components";
import {FollowBar} from "@/components";
import LoginModal from "@/components/Modal/LoginModal";
import RegisterModal from "@/components/Modal/RegisterModal";
import { Providers } from "@/components";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LoginModal />
        <RegisterModal/>
        <main className="min-h-screen bg-black">
          <div className="container h-full  mx-auto xl:px-30 max-w-6xl">
            <div className="grid grid-cols-4 min-h-screen">
                <div className="col-span-1">
                <Sidebar />
                </div>
              <div className="col-span-3 lg:col-span-2 border-x-[1px] bg-neutral-950 ">
                <Providers>
                {children}
                </Providers>
              </div>  

              <FollowBar /> 
            </div>            
          </div>
        </main>
      </body>
    </html>
  );
}
